services:
  neural-colmap:
    build:
      context: .
      dockerfile: Dockerfile
    image: colmap-neural:latest
    container_name: colmap-neural-dev
    volumes:
      - ./:/app                          # Mount project directory
      - ./data:/app/data                 # Mount data directory
      - ./models:/app/models             # Mount models directory
      - ./benchmark-results:/app/benchmark-results  # Mount benchmark results
    ports:
      - "8888:8888"                      # For Jupyter if needed
    tty: true
    stdin_open: true
    # Override the entrypoint in Dockerfile to get an interactive shell
    entrypoint: ["/bin/bash"]
    
  # Separate service for benchmarking
  benchmark:
    image: colmap-neural:latest
    container_name: colmap-neural-benchmark
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./models:/app/models
      - ./benchmark-results:/app/benchmark-results
    command: python3 /app/scripts/benchmark.py